### ISSUE TITLE
About implementation!

### ISSUE THREAD

**Issue by muxiddin19** [Oli21-chen/STM-spatiotemporal-and-motion-encoding#1]
Great work! Hello Dear! Can you provide some details about its implementation?
I wanted to run, but I failed to make data for it from the videoframes.  It was essential on my ongoing paper, which is related to human action recognition too. I would appreciate it if you guided me through this process. Thank you for your hard work!

**Comment by Oli21-chen** [comment]
Hi, thank you for your comments. The input shape is (32,224,224,3), in classic Tensorflow format (T, H, W, C). Some of these codes follow the official code of Resnet. I can directly do the experiment by switching the model from 'import' . So if your data format can run on resnet, it should be ok on this one.
